/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include"APIs.h"

void Clock_INIT(void)
{
    //set on the clock for PORTA
    RCC_GPIOA_CLK_EN();
    //set on the clock for PORTB
    RCC_GPIOB_CLK_EN();
    //set on the clock for AFIO
    RCC_GPIOC_CLK_EN();
    RCC_AFIO_CLK_EN();
    RCC_TIM2_CLK_Enable();
    RCC_TIM3_CLK_Enable();
    RCC_TIM4_CLK_Enable();
    RCC_ADC1_CLK_Enable();
}

int main (){
	Clock_INIT();
	GPIO_Pinconfig_t pinconfig ;
	pinconfig.GPIO_MODE = GPIO_MODE_OUTPUT_OD  ;
	pinconfig.GPIO_OUTPUT_Speed = GPIO_speed_2M ;
	pinconfig.pinNumber = GPIO_PIN_13 ;
	MCAL_GPIO_Init(GPIOC, &pinconfig) ;

	pinconfig.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	pinconfig.GPIO_OUTPUT_Speed = GPIO_speed_10M ;
	pinconfig.pinNumber = GPIO_PIN_9 ;
	MCAL_GPIO_Init(GPIOB, &pinconfig) ;
	MCAL_GPIO_WritePin(GPIOB, GPIO_PIN_9, SET);

	pinconfig.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	pinconfig.GPIO_OUTPUT_Speed = GPIO_speed_10M ;
	pinconfig.pinNumber = GPIO_PIN_8 ;
	MCAL_GPIO_Init(GPIOB, &pinconfig) ;
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_8, RESET);

	TIMx_config_t  TIMx_Config;
	TIMx_Config.COUNT_MODE=TIMx_COUNT_MODE_UP;
	TIMx_Config.MODE=TIMx_MODE_PWM2;
	TIMx_Config.Prescalers=7;  // timer clock 1mhz
	MCAL_TIMx_Init(TIM2, &TIMx_Config , CH1);
	MCAL_TIMx_Set_Compare_Value(TIM2,20000,CH2);
	MCAL_TIMx_Set_TOP_Value(TIM2, 20000);
	MCAL_TIMx_Init(TIM2, &TIMx_Config , CH2);
	MCAL_TIMx_Set_Compare_Value(TIM2,2000,CH2);
	MCAL_TIMx_Init(TIM2, &TIMx_Config , CH3);
	MCAL_TIMx_Set_Compare_Value(TIM2,20000,CH3);
	MCAL_TIMx_Init(TIM2, &TIMx_Config , CH4);
	MCAL_TIMx_Set_Compare_Value(TIM2,10000,CH4);

	while(1)
	{
		MCAL_GPIO_TogglePin(GPIOC, GPIO_PIN_13);
		delay_ms(1000);

		MCAL_TIMx_Set_Compare_Value(TIM2,0,CH1);
		MCAL_TIMx_Set_Compare_Value(TIM2,20000,CH2);
		MCAL_TIMx_Set_Compare_Value(TIM2,0,CH3);
		MCAL_TIMx_Set_Compare_Value(TIM2,0,CH4);
		delay_ms(2000);
		MCAL_TIMx_Set_Compare_Value(TIM2,1000,CH1);
		MCAL_TIMx_Set_Compare_Value(TIM2,15000,CH2);
		MCAL_TIMx_Set_Compare_Value(TIM2,5000,CH3);
		MCAL_TIMx_Set_Compare_Value(TIM2,5000,CH4);
		delay_ms(2000);
		MCAL_TIMx_Set_Compare_Value(TIM2,3000,CH1);
		MCAL_TIMx_Set_Compare_Value(TIM2,10000,CH2);
		MCAL_TIMx_Set_Compare_Value(TIM2,10000,CH3);
		MCAL_TIMx_Set_Compare_Value(TIM2,10000,CH4);
		delay_ms(2000);
		MCAL_TIMx_Set_Compare_Value(TIM2,5000,CH1);
		MCAL_TIMx_Set_Compare_Value(TIM2,5000,CH2);
		MCAL_TIMx_Set_Compare_Value(TIM2,15000,CH3);
		MCAL_TIMx_Set_Compare_Value(TIM2,15000,CH4);
		delay_ms(2000);
		MCAL_TIMx_Set_Compare_Value(TIM2,20000,CH1);
		MCAL_TIMx_Set_Compare_Value(TIM2,0,CH2);
		MCAL_TIMx_Set_Compare_Value(TIM2,20000,CH3);
		MCAL_TIMx_Set_Compare_Value(TIM2,20000,CH4);
		delay_ms(2000);

	}
	return 0;
}
